# Documentation: https://docs.gitlab.com/ce/ci/yaml/README.html


image: node:8.9.0

# And to cache them as well.
cache:
  paths:
    - node_modules/

stages:
  - build
  - tests

build:
  stage: build
  only:
    - dev
    - web
  before_script: 
    - npm install 
  script:
    - CI=true export NODE_OPTIONS=--max_old_space_size=2048; npm run build

tests:
  stage: tests
  only:
    - dev
    - web
  before_script: 
    - npm install 
  script:
    # Using --forceExit because could find what's keeping jest from exiting and --detectOpenHandles does not show anything, so might be a bug from jest
    # In this issue lot of people are having this (https://github.com/facebook/jest/issues/1456)
    # Like here: https://github.com/facebook/jest/issues/1456#issuecomment-414250666
    - CI=true npm test -- --forceExit --coverage
  coverage: /All files[^|]*\|[^|]*\s+([\d\.]+)/